import { createClient } from '@sanity/client'

const client = createClient({
  projectId: 'vgacjlhu',
  dataset: 'production',
  token: process.env.SANITY_API_WRITE_TOKEN || '',
  useCdn: false,
  apiVersion: '2025-01-01'
})

async function bulkCreateResources() {
  console.log('📚 Creating 20 new resources...\n')

  const resources = [
    { _id: 'resource-1', _type: 'resource', title: 'Advanced MetBase Features: Automation and Custom Solutions for Complex Quality Management', slug: { current: 'advanced-metbase-features' }, category: 'metbase-integration', excerpt: 'Master advanced MetBase automation capabilities and custom development for complex quality management requirements', content: 'Advanced MetBase Features: Automation and Custom Solutions for Complex Quality Management', difficulty: 'Expert', readTime: '7 min', publishDate: '2024-11-06T00:00:00Z', author: 'IIS Engineering Team', featured: true, published: true, tags: ['MetBase', 'Automation', 'Quality Management'] },
    { _id: 'resource-2', _type: 'resource', title: 'Statistical Analysis and Reporting with MetBase: SPC Analysis and Quality Data Intelligence', slug: { current: 'statistical-analysis-metbase' }, category: 'metbase-integration', excerpt: 'Master statistical analysis and reporting capabilities in MetBase for comprehensive quality data intelligence', content: 'Statistical Analysis and Reporting with MetBase: SPC Analysis and Quality Data Intelligence', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-11-05T00:00:00Z', author: 'IIS Engineering Team', featured: true, published: true, tags: ['MetBase', 'SPC', 'Quality Analysis'] },
    { _id: 'resource-3', _type: 'resource', title: 'MetBase Setup and Integration with Measurement Equipment: Quality Data Management System Implementation', slug: { current: 'metbase-setup-integration' }, category: 'metbase-integration', excerpt: 'Master MetBase setup and integration with measurement equipment for comprehensive quality data management', content: 'MetBase Setup and Integration with Measurement Equipment: Quality Data Management System Implementation', difficulty: 'Advanced', readTime: '9 min', publishDate: '2024-11-04T00:00:00Z', author: 'IIS Engineering Team', featured: false, published: true, tags: ['MetBase', 'Integration', 'Data Management'] },
    { _id: 'resource-4', _type: 'resource', title: 'Supplier Management and Continuous Improvement in AS9100: Advanced Quality System Optimization', slug: { current: 'supplier-management-as9100' }, category: 'as9100-quality', excerpt: 'Master AS9100 supplier management requirements and continuous improvement strategies', content: 'Supplier Management and Continuous Improvement in AS9100: Advanced Quality System Optimization', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-11-03T00:00:00Z', author: 'IIS Engineering Team', featured: false, published: true, tags: ['AS9100', 'Supplier Management', 'Quality'] },
    { _id: 'resource-5', _type: 'resource', title: 'Risk Management and Configuration Control in AS9100: Advanced Aerospace Quality System Controls', slug: { current: 'risk-management-as9100' }, category: 'as9100-quality', excerpt: 'Master AS9100 risk management and configuration control requirements for aerospace quality systems', content: 'Risk Management and Configuration Control in AS9100: Advanced Aerospace Quality System Controls', difficulty: 'Advanced', readTime: '9 min', publishDate: '2024-11-02T00:00:00Z', author: 'IIS Engineering Team', featured: false, published: true, tags: ['AS9100', 'Risk Management', 'Aerospace'] },
    { _id: 'resource-6', _type: 'resource', title: 'AS9100 Implementation and Certification Process: Aerospace Quality Management System Guide', slug: { current: 'as9100-implementation-certification' }, category: 'as9100-quality', excerpt: 'Master AS9100 implementation and certification for aerospace quality management systems', content: 'AS9100 Implementation and Certification Process: Aerospace Quality Management System Guide', difficulty: 'Advanced', readTime: '12 min', publishDate: '2024-11-01T00:00:00Z', author: 'IIS Engineering Team', featured: true, published: true, tags: ['AS9100', 'Certification', 'Aerospace Quality'] },
    { _id: 'resource-7', _type: 'resource', title: 'Advanced CNC Techniques: 5-Axis and Multi-Setup Strategies for Complex Geometry Machining', slug: { current: 'advanced-cnc-techniques' }, category: 'cnc-manufacturing', excerpt: 'Master advanced CNC techniques including 5-axis machining, multi-setup strategies, and complex geometry programming', content: 'Advanced CNC Techniques: 5-Axis and Multi-Setup Strategies for Complex Geometry Machining', difficulty: 'Expert', readTime: '10 min', publishDate: '2024-10-31T00:00:00Z', author: 'IIS Manufacturing Engineers', featured: true, published: true, tags: ['CNC', '5-Axis', 'Machining'] },
    { _id: 'resource-8', _type: 'resource', title: 'Material Considerations for Precision CNC Machining: Optimization Strategies for Different Alloys', slug: { current: 'material-cnc-machining' }, category: 'cnc-manufacturing', excerpt: 'Master material-specific CNC machining strategies, tool selection, and parameter optimization', content: 'Material Considerations for Precision CNC Machining: Optimization Strategies for Different Alloys', difficulty: 'Advanced', readTime: '9 min', publishDate: '2024-10-30T00:00:00Z', author: 'IIS Manufacturing Engineers', featured: false, published: true, tags: ['CNC', 'Materials', 'Machining'] },
    { _id: 'resource-9', _type: 'resource', title: 'Surface Finish Requirements and Achievement: CNC Machining Surface Quality Control', slug: { current: 'surface-finish-cnc' }, category: 'cnc-manufacturing', excerpt: 'Master surface finish specifications, measurement techniques, and achievement methods for CNC machining', content: 'Surface Finish Requirements and Achievement: CNC Machining Surface Quality Control', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-10-29T00:00:00Z', author: 'IIS Manufacturing Engineers', featured: false, published: true, tags: ['Surface Finish', 'Quality Control', 'CNC'] },
    { _id: 'resource-10', _type: 'resource', title: 'CNC Machining Tolerance Capabilities and Specifications: Achieving Precision in Manufacturing', slug: { current: 'cnc-tolerance-capabilities' }, category: 'cnc-manufacturing', excerpt: 'Master CNC machining tolerance capabilities, achievable specifications, and factors affecting precision', content: 'CNC Machining Tolerance Capabilities and Specifications: Achieving Precision in Manufacturing', difficulty: 'Advanced', readTime: '10 min', publishDate: '2024-10-28T00:00:00Z', author: 'IIS Manufacturing Engineers', featured: false, published: true, tags: ['Tolerance', 'Precision', 'CNC'] },
    { _id: 'resource-11', _type: 'resource', title: 'GD&T Measurement and Verification Techniques: CMM Programming and Functional Gaging Methods', slug: { current: 'gdt-measurement-verification' }, category: 'gdt-fundamentals', excerpt: 'Master practical GD&T measurement methods, CMM programming techniques, and functional gaging strategies', content: 'GD&T Measurement and Verification Techniques: CMM Programming and Functional Gaging Methods', difficulty: 'Advanced', readTime: '9 min', publishDate: '2024-10-27T00:00:00Z', author: 'IIS Metrology Team', featured: true, published: true, tags: ['GD&T', 'CMM', 'Measurement'] },
    { _id: 'resource-12', _type: 'resource', title: 'Position Tolerance and Material Condition Modifiers: Advanced GD&T Applications and Bonus Tolerance', slug: { current: 'position-tolerance-gdt' }, category: 'gdt-fundamentals', excerpt: 'Master position tolerance applications, MMC/LMC material condition modifiers, and bonus tolerance calculations', content: 'Position Tolerance and Material Condition Modifiers: Advanced GD&T Applications and Bonus Tolerance', difficulty: 'Advanced', readTime: '10 min', publishDate: '2024-10-26T00:00:00Z', author: 'IIS Metrology Team', featured: false, published: true, tags: ['GD&T', 'Position Tolerance', 'Bonus Tolerance'] },
    { _id: 'resource-13', _type: 'resource', title: 'Datum Reference Frames and Establishment: Mastering Coordinate System Definition in GD&T', slug: { current: 'datum-reference-frames' }, category: 'gdt-fundamentals', excerpt: 'Master datum reference frame establishment, coordinate system definition, and the 3-2-1 principle in GD&T', content: 'Datum Reference Frames and Establishment: Mastering Coordinate System Definition in GD&T', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-10-25T00:00:00Z', author: 'IIS Metrology Team', featured: false, published: true, tags: ['GD&T', 'Datum', 'Reference Frames'] },
    { _id: 'resource-14', _type: 'resource', title: 'GD&T Symbols and Basic Principles: Understanding Geometric Dimensioning and Tolerancing Fundamentals', slug: { current: 'gdt-symbols-basics' }, category: 'gdt-fundamentals', excerpt: 'Master fundamental GD&T symbols, principles, and applications per ASME Y14.5 standard', content: 'GD&T Symbols and Basic Principles: Understanding Geometric Dimensioning and Tolerancing Fundamentals', difficulty: 'Intermediate', readTime: '9 min', publishDate: '2024-10-24T00:00:00Z', author: 'IIS Metrology Team', featured: true, published: true, tags: ['GD&T', 'ASME Y14.5', 'Symbols'] },
    { _id: 'resource-15', _type: 'resource', title: 'Customer Requirements and FAI Approval Process: Navigating Aerospace and Defense FAI Standards', slug: { current: 'customer-fai-approval' }, category: 'first-article-inspection', excerpt: 'Navigate complex customer-specific FAI requirements and approval processes for aerospace and defense programs', content: 'Customer Requirements and FAI Approval Process: Navigating Aerospace and Defense FAI Standards', difficulty: 'Advanced', readTime: '7 min', publishDate: '2024-10-23T00:00:00Z', author: 'IIS Engineering Team', featured: false, published: true, tags: ['FAI', 'Customer Requirements', 'Aerospace'] },
    { _id: 'resource-16', _type: 'resource', title: 'FAI Measurement and Inspection Procedures: Systematic AS9102 Compliance', slug: { current: 'fai-measurement-procedures' }, category: 'first-article-inspection', excerpt: 'Master systematic FAI measurement procedures, inspection planning, and AS9102 compliance verification', content: 'FAI Measurement and Inspection Procedures: Systematic AS9102 Compliance', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-10-22T00:00:00Z', author: 'IIS Engineering Team', featured: false, published: true, tags: ['FAI', 'AS9102', 'Inspection'] },
    { _id: 'resource-17', _type: 'resource', title: 'AS9102 Forms and Documentation Requirements: Complete FAI Compliance Guide', slug: { current: 'as9102-forms-documentation' }, category: 'first-article-inspection', excerpt: 'Master AS9102 Form 1, Form 2, and Form 3 completion for First Article Inspection compliance', content: 'AS9102 Forms and Documentation Requirements: Complete FAI Compliance Guide', difficulty: 'Advanced', readTime: '10 min', publishDate: '2024-10-21T00:00:00Z', author: 'IIS Engineering Team', featured: true, published: true, tags: ['AS9102', 'FAI', 'Documentation'] },
    { _id: 'resource-18', _type: 'resource', title: 'CMM Error Analysis and Troubleshooting: Identifying and Correcting Measurement Issues', slug: { current: 'cmm-error-analysis' }, category: 'cmm-inspection', excerpt: 'Master CMM error analysis, measurement uncertainty assessment, and systematic troubleshooting techniques', content: 'CMM Error Analysis and Troubleshooting: Identifying and Correcting Measurement Issues', difficulty: 'Advanced', readTime: '8 min', publishDate: '2024-10-20T00:00:00Z', author: 'IIS Metrology Team', featured: false, published: true, tags: ['CMM', 'Error Analysis', 'Troubleshooting'] },
    { _id: 'resource-19', _type: 'resource', title: 'CMM Measurement Strategies and Planning: Optimizing Accuracy and Efficiency', slug: { current: 'cmm-measurement-strategies' }, category: 'cmm-inspection', excerpt: 'Master CMM measurement strategy development, datum establishment, and measurement sequence planning', content: 'CMM Measurement Strategies and Planning: Optimizing Accuracy and Efficiency', difficulty: 'Advanced', readTime: '9 min', publishDate: '2024-10-19T00:00:00Z', author: 'IIS Metrology Team', featured: true, published: true, tags: ['CMM', 'Measurement', 'Strategy'] },
    { _id: 'resource-20', _type: 'resource', title: 'CMM Probe Selection and Configuration: Choosing the Right Tool for Precision', slug: { current: 'cmm-probe-selection' }, category: 'cmm-inspection', excerpt: 'Master CMM probe selection, configuration, and qualification procedures for optimal measurement accuracy', content: 'CMM Probe Selection and Configuration: Choosing the Right Tool for Precision', difficulty: 'Intermediate', readTime: '7 min', publishDate: '2024-10-18T00:00:00Z', author: 'IIS Metrology Team', featured: false, published: true, tags: ['CMM', 'Probe', 'Configuration'] },
  ]

  let created = 0
  let errors = 0

  for (const resource of resources) {
    try {
      await client.create(resource)
      created++
      process.stdout.write('✓')
    } catch (error: any) {
      errors++
      process.stdout.write('E')
      console.error(`\n  Error on ${resource._id}:`, error.message)
    }
  }

  console.log(`\n\n✅ Successfully created ${created} out of 20 resources`)
  if (errors > 0) {
    console.log(`⚠️  ${errors} errors (may include duplicates)`)
  }
}

bulkCreateResources().catch(console.error)
