/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  published?: boolean;
  sections?: Array<{
    _key: string;
  } & HeroSection | {
    _key: string;
  } & RichTextSection | {
    _key: string;
  } & CtaSection>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PageContent = {
  _id: string;
  _type: "pageContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageName?: string;
  industriesPage?: {
    hero?: {
      badge?: string;
      title?: string;
      subtitle?: string;
      description?: string;
      descriptionRich?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      titleSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
      descriptionSize?: "xs" | "sm" | "base" | "lg" | "xl";
      backgroundImage?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      backgroundImageUrl?: string;
      buttons?: Array<{
        label?: string;
        href?: string;
        variant?: string;
        _key: string;
      }>;
    };
    header?: {
      title?: string;
      description?: string;
    };
    cta?: {
      heading?: string;
      description?: string;
      primaryButton?: {
        label?: string;
        href?: string;
      };
      secondaryButton?: {
        label?: string;
        href?: string;
      };
    };
  };
  resourcesPage?: {
    hero?: {
      badge?: string;
      title?: string;
      subtitle?: string;
      description?: string;
      descriptionRich?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      titleSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
      descriptionSize?: "xs" | "sm" | "base" | "lg" | "xl";
      backgroundImage?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      backgroundImageUrl?: string;
      buttons?: Array<{
        label?: string;
        href?: string;
        variant?: string;
        _key: string;
      }>;
    };
    header?: {
      title?: string;
      description?: string;
      eyebrow?: string;
    };
  };
  capabilities?: Array<{
    label?: string;
    value?: string;
    description?: string;
    _key: string;
  }>;
  qualityAssurance?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    backgroundImageUrl?: string;
    badge?: string;
    title?: string;
    subtitle?: string;
    description?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    titleSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
    descriptionSize?: "xs" | "sm" | "base" | "lg" | "xl";
    buttons?: Array<{
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  servicesPage?: {
    hero?: {
      badge?: string;
      title?: string;
      subtitle?: string;
      description?: string;
      backgroundImage?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      backgroundImageUrl?: string;
      buttons?: Array<{
        label?: string;
        href?: string;
        variant?: "primary" | "secondary";
        _key: string;
      }>;
    };
    qualityIntro?: string;
    qualityImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    qualityImageUrl?: string;
    cta?: {
      heading?: string;
      description?: string;
      primaryButton?: {
        label?: string;
        href?: string;
      };
      secondaryButton?: {
        label?: string;
        href?: string;
      };
    };
  };
  sections?: Array<{
    title?: string;
    description?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type UiText = {
  _id: string;
  _type: "uiText";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  buttons?: {
    getQuote?: string;
    contactUs?: string;
    viewServices?: string;
    viewIndustries?: string;
    learnMore?: string;
  };
  sections?: {
    ctaHeading?: string;
    ctaDescription?: string;
    serviceOfferings?: string;
    ourCapabilities?: string;
  };
};

export type Metbase = {
  _id: string;
  _type: "metbase";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    badge?: string;
    badgeIconName?: string;
    title?: string;
    titleHighlight?: string;
    subtitle?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  overview?: {
    title?: string;
    description?: string;
    highlights?: Array<{
      enabled?: boolean;
      text?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  features?: {
    title?: string;
    description?: string;
    items?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  analysisTool?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    capabilities?: Array<{
      enabled?: boolean;
      text?: string;
      _key: string;
    }>;
  };
  systemIntegration?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    benefits?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  closedLoop?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
  };
  cta?: {
    title?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type ErrorPages = {
  _id: string;
  _type: "errorPages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notFound?: {
    heading?: string;
    description?: string;
    popularLinksHeading?: string;
    popularLinks?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    errorCode?: string;
  };
  globalError?: {
    heading?: string;
    description?: string;
    tryAgainButtonText?: string;
    supportMessagePrefix?: string;
    supportLinkText?: string;
  };
};

export type SupplierRequirements = {
  _id: string;
  _type: "supplierRequirements";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    badges?: Array<{
      iconName?: string;
      text?: string;
      _key: string;
    }>;
    title?: string;
    titleHighlight?: string;
    description?: string;
    subtitle?: string;
    versionStatus?: string;
    effectiveDate?: string;
    reviewPeriod?: string;
  };
  introSection?: {
    title?: string;
    description?: string;
  };
  sections?: Array<{
    id?: string;
    number?: string;
    title?: string;
    iconName?: string;
    content?: string;
    color?: string;
    _key: string;
  }>;
  requirements?: Array<{
    number?: string;
    title?: string;
    iconName?: string;
    icon?: string;
    content?: string;
    description?: string;
    additional?: string;
    list?: Array<{
      item?: string;
      _key: string;
    }>;
    details?: Array<{
      detail?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  additionalSections?: Array<{
    number?: string;
    title?: string;
    iconName?: string;
    content?: string;
    list?: Array<{
      item?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  footerNote?: {
    iconName?: string;
    heading?: string;
    content?: string;
  };
  compliance?: {
    title?: string;
    description?: string;
    certifications?: Array<{
      certification?: string;
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type Terms = {
  _id: string;
  _type: "terms";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    title?: string;
    subtitle?: string;
    effectiveDate?: string;
    version?: string;
  };
  title?: string;
  lastUpdated?: string;
  sections?: Array<{
    icon?: string;
    title?: string;
    heading?: string;
    content?: string;
    subsections?: Array<{
      subheading?: string;
      text?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  contact?: {
    heading?: string;
    description?: string;
    email?: string;
    phone?: string;
    department?: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type Careers = {
  _id: string;
  _type: "careers";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    backgroundImageUrl?: string;
    badge?: string;
    badgeIconName?: string;
    title?: string;
    titleHighlight?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  benefits?: {
    title?: string;
    description?: string;
    items?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  values?: {
    title?: string;
    description?: string;
    items?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  opportunities?: {
    title?: string;
    description?: string;
  };
  whyWorkHere?: {
    heading?: string;
    paragraph1?: string;
    paragraph2?: string;
    paragraph3?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    imageUrl?: string;
  };
  cta?: {
    title?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    backgroundImageUrl?: string;
    badge?: string;
    badgeIconName?: string;
    title?: string;
    titleHighlight?: string;
    description?: string;
    buttonLabel?: string;
    buttonHref?: string;
  };
  contactInfo?: {
    heading?: string;
    description?: string;
    addressLine1?: string;
    addressLine2?: string;
    addressLine3?: string;
    phone?: string;
    phoneLink?: string;
    email?: string;
    hoursLine1?: string;
    hoursLine2?: string;
    phoneDescription?: string;
    emailDescription?: string;
    submitButtonText?: string;
    consultationHeading?: string;
  };
  locationImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  locationDescription?: string;
  certifications?: Array<{
    enabled?: boolean;
    certification?: string;
    _key: string;
  }>;
  bottomStats?: Array<{
    enabled?: boolean;
    iconName?: string;
    text?: string;
    animated?: boolean;
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    backgroundImageUrl?: string;
    badge?: string;
    badgeIconName?: string;
    title?: string;
    titleHighlight?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  companyStats?: Array<{
    enabled?: boolean;
    label?: string;
    value?: string;
    description?: string;
    _key: string;
  }>;
  story?: {
    title?: string;
    paragraph1?: string;
    paragraph2?: string;
    paragraph3?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    imageUrl?: string;
  };
  timeline?: {
    title?: string;
    description?: string;
    milestones?: Array<{
      enabled?: boolean;
      year?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  values?: {
    title?: string;
    description?: string;
    items?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      iconName?: string;
      bullets?: Array<{
        text?: string;
        _key: string;
      }>;
      _key: string;
    }>;
  };
  capabilities?: Array<{
    enabled?: boolean;
    title?: string;
    description?: string;
    items?: Array<{
      item?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  certifications?: Array<{
    enabled?: boolean;
    certification?: string;
    _key: string;
  }>;
  leadership?: {
    title?: string;
    description?: string;
    team?: Array<{
      enabled?: boolean;
      photo?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      photoUrl?: string;
      name?: string;
      title?: string;
      experience?: string;
      background?: string;
      focus?: string;
      _key: string;
    }>;
  };
  cta?: {
    title?: string;
    description?: string;
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: {
    description?: string;
    foundedYear?: string;
    certifications?: string;
  };
  social?: {
    linkedin?: string;
    twitter?: string;
    facebook?: string;
  };
  servicesHeading?: string;
  servicesLinks?: Array<{
    enabled?: boolean;
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  resourcesHeading?: string;
  resourcesLinks?: Array<{
    enabled?: boolean;
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  quickLinksHeading?: string;
  quickLinks?: Array<{
    enabled?: boolean;
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  contactHeading?: string;
  contact?: {
    email?: string;
    phone?: string;
    phoneLink?: string;
    address?: string;
  };
  copyright?: string;
  certificationBadges?: Array<{
    enabled?: boolean;
    label?: string;
    iconName?: string;
    iconColor?: string;
    _type: "certificationBadge";
    _key: string;
  }>;
};

export type IndustriesPage = {
  _id: string;
  _type: "industriesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    heading?: string;
    headingHighlight?: string;
    subheading?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _key: string;
    }>;
  };
  content?: {
    overviewTitle?: string;
    overviewStats?: Array<{
      enabled?: boolean;
      label?: string;
      value?: string;
      description?: string;
      _key: string;
    }>;
    industries?: Array<{
      enabled?: boolean;
      name?: string;
      slug?: Slug;
      description?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      applications?: Array<string>;
      stats?: Array<{
        label?: string;
        value?: string;
        _key: string;
      }>;
      certifications?: Array<string>;
      expertise?: Array<string>;
      icon?: string;
      cardCtaText?: string;
      _key: string;
    }>;
    industriesSection?: {
      title?: string;
      description?: string;
    };
    whyChooseSection?: {
      title?: string;
      description?: string;
    };
    whyChooseUs?: Array<{
      enabled?: boolean;
      title?: string;
      description?: string;
      icon?: string;
      features?: Array<string>;
      _key: string;
    }>;
    resultsSection?: {
      title?: string;
      description?: string;
    };
    provenResults?: Array<{
      enabled?: boolean;
      metric?: string;
      value?: string;
      description?: string;
      _key: string;
    }>;
  };
  cta?: {
    heading?: string;
    description?: string;
    primaryButton?: {
      enabled?: boolean;
      label?: string;
      href?: string;
    };
    secondaryButton?: {
      enabled?: boolean;
      label?: string;
      href?: string;
    };
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    keywords?: Array<string>;
  };
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    heading?: string;
    headingHighlight?: string;
    description?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    buttons?: Array<{
      enabled?: boolean;
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      _type: "button";
      _key: string;
    }>;
  };
  content?: {
    sectionTitle?: string;
    sectionDescription?: string;
    capabilities?: Array<{
      enabled?: boolean;
      label?: string;
      value?: string;
      description?: string;
      _type: "capability";
      _key: string;
    }>;
    qualityAssurance?: Array<{
      enabled?: boolean;
      title?: string;
      _key: string;
    }>;
  };
  cta?: {
    heading?: string;
    description?: string;
    buttons?: Array<{
      label?: string;
      href?: string;
      variant?: "primary" | "secondary";
      enabled?: boolean;
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    keywords?: Array<string>;
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    enabled?: boolean;
    backgroundGradient?: "from-blue-600 to-indigo-600" | "from-blue-800 to-indigo-800" | "from-zinc-800 to-zinc-900" | "from-indigo-600 to-purple-600" | "bg-blue-600" | "bg-zinc-900" | "custom";
    headingTextColor?: "text-tone-inverse" | "text-tone-inverse/90" | "text-zinc-900" | "text-zinc-600" | "text-blue-600" | "custom";
    taglineTextColor?: "text-tone-inverse/80" | "text-tone-inverse" | "text-zinc-300" | "text-zinc-400" | "text-zinc-600" | "custom";
    heroVerticalPadding?: "py-16 md:py-20" | "py-20 md:py-24" | "py-24 md:py-32" | "py-32 md:py-40" | "custom";
    word1?: string;
    word2?: string;
    word3?: string;
    heroFontSize?: "text-[2.5rem] sm:text-[3rem] md:text-[3.5rem] lg:text-[4rem]" | "text-[2.75rem] sm:text-[3.25rem] md:text-[3.75rem] lg:text-[4.5rem]" | "text-[3rem] sm:text-[3.5rem] md:text-[4rem] lg:text-[4.5rem] xl:text-[5rem]" | "text-[3.5rem] sm:text-[4rem] md:text-[5rem] lg:text-[5.5rem] xl:text-[6rem]" | "custom";
    tagline?: string;
    slides?: Array<{
      enabled?: boolean;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
      };
      _key: string;
    }>;
    badges?: Array<{
      enabled?: boolean;
      text?: string;
      _key: string;
    }>;
    ctaPrimary?: {
      text?: string;
      href?: string;
    };
    ctaSecondary?: {
      text?: string;
      href?: string;
    };
    ctaTertiary?: {
      text?: string;
      href?: string;
    };
  };
  clientLogos?: {
    enabled?: boolean;
    eyebrow?: string;
    logos?: Array<{
      enabled?: boolean;
      name?: string;
      logo?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      href?: string;
      _key: string;
    }>;
    animationSpeed?: "slow" | "medium" | "fast";
    grayscale?: boolean;
  };
  stats?: {
    enabled?: boolean;
    title?: string;
    subtitle?: string;
    backgroundColor?: "bg-zinc-50" | "bg-white" | "bg-blue-50" | "bg-gray-100" | "custom";
    titleTextColor?: "text-zinc-900" | "text-black" | "text-zinc-700" | "text-blue-600" | "custom";
    subtitleTextColor?: "text-zinc-600" | "text-zinc-700" | "text-zinc-500" | "text-blue-600" | "custom";
    items?: Array<{
      enabled?: boolean;
      value?: string;
      label?: string;
      description?: string;
      _key: string;
    }>;
  };
  servicesSection?: {
    enabled?: boolean;
    eyebrow?: string;
    headingWord1?: string;
    headingWord2?: string;
    description?: string;
    subdescription?: string;
    headingColor?: "text-zinc-900" | "text-black" | "text-zinc-700" | "text-blue-600" | "custom";
    eyebrowColor?: "text-blue-600" | "text-blue-700" | "text-indigo-600" | "text-zinc-700" | "text-zinc-600" | "custom";
    cta?: {
      enabled?: boolean;
      text?: string;
      href?: string;
      variant?: "primary" | "secondary";
    };
    cardCtaText?: string;
  };
  industriesSection?: {
    enabled?: boolean;
    eyebrow?: string;
    heading?: string;
    description?: string;
    subdescription?: string;
    header?: {
      eyebrow?: string;
      title?: string;
      titleHighlight?: string;
      description?: string;
    };
    headingColor?: "text-zinc-900" | "text-black" | "text-zinc-700" | "text-blue-600" | "custom";
    eyebrowColor?: "text-blue-600" | "text-blue-700" | "text-indigo-600" | "text-zinc-700" | "text-zinc-600" | "custom";
    cardCtaText?: string;
  };
  technicalSpecs?: {
    enabled?: boolean;
    title?: string;
    subtitle?: string;
    specs?: Array<{
      enabled?: boolean;
      label?: string;
      value?: string;
      description?: string;
      iconName?: string;
      gradient?: string;
      _key: string;
    }>;
  };
  imageShowcase?: {
    enabled?: boolean;
    header?: {
      eyebrow?: string;
      title?: string;
      titleHighlight?: string;
      description?: string;
    };
    backgroundColor?: "bg-white" | "bg-zinc-50" | "bg-blue-50" | "bg-gray-100" | "custom";
    titleColor?: "text-zinc-900" | "text-black" | "text-zinc-700" | "text-blue-600" | "custom";
    highlightColor?: "text-blue-600" | "text-blue-700" | "text-indigo-600" | "text-zinc-700" | "custom";
    showcaseImages?: Array<{
      enabled?: boolean;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      src?: string;
      alt?: string;
      title?: string;
      category?: string;
      href?: string;
      _key: string;
    }>;
    stats?: Array<{
      enabled?: boolean;
      iconName?: string;
      value?: string;
      label?: string;
      _key: string;
    }>;
    cta?: {
      title?: string;
      description?: string;
      buttons?: Array<{
        enabled?: boolean;
        text?: string;
        href?: string;
        variant?: "primary" | "secondary";
        _key: string;
      }>;
    };
  };
  operationalExcellence?: {
    enabled?: boolean;
    heading?: string;
    description?: string;
    benefits?: Array<{
      enabled?: boolean;
      iconName?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    certifications?: Array<{
      enabled?: boolean;
      label?: string;
      iconName?: string;
      _key: string;
    }>;
  };
  resourcesSection?: {
    enabled?: boolean;
    header?: {
      badge?: string;
      title?: string;
      description?: string;
    };
    backgroundColor?: "bg-white" | "bg-zinc-50" | "bg-zinc-100" | "bg-blue-50" | "custom";
    titleColor?: "text-zinc-900" | "text-black" | "text-zinc-700" | "text-blue-600" | "custom";
    badgeColor?: "text-blue-600" | "text-blue-700" | "text-indigo-600" | "text-zinc-700" | "custom";
    featuredSeries?: Array<{
      enabled?: boolean;
      title?: string;
      slug?: string;
      description?: string;
      articleCount?: number;
      readTime?: string;
      difficulty?: "Beginner" | "Intermediate" | "Advanced";
      icon?: string;
      gradient?: string;
      _key: string;
    }>;
    benefits?: Array<{
      enabled?: boolean;
      iconName?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    cta?: {
      title?: string;
      description?: string;
      buttons?: Array<{
        enabled?: boolean;
        text?: string;
        href?: string;
        variant?: "primary" | "secondary";
        _key: string;
      }>;
    };
    additionalSeriesText?: string;
  };
  cta?: {
    enabled?: boolean;
    title?: string;
    subtitle?: string;
    backgroundColor?: "from-blue-600 to-indigo-600" | "from-blue-800 to-indigo-800" | "from-zinc-800 to-zinc-900" | "from-indigo-600 to-purple-600" | "bg-blue-600" | "bg-zinc-900" | "custom";
    titleColor?: "text-tone-inverse" | "text-tone-inverse/90" | "text-zinc-100" | "text-blue-100" | "custom";
    subtitleColor?: "text-tone-inverse/90" | "text-tone-inverse" | "text-zinc-200" | "text-tone-inverse/80" | "custom";
    buttons?: Array<{
      enabled?: boolean;
      text?: string;
      href?: string;
      variant?: "default" | "secondary";
      _key: string;
    }>;
    badge?: string;
    certifications?: Array<{
      enabled?: boolean;
      icon?: string;
      text?: string;
      _key: string;
    }>;
    trustMessage?: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  topBar?: {
    showPhone?: boolean;
    phone?: string;
    phoneLink?: string;
    showEmail?: boolean;
    email?: string;
    emailLink?: string;
    showCertifications?: boolean;
    certifications?: string;
  };
  menuItems?: Array<{
    _key: string;
  } & NavItem | {
    name?: string;
    href?: string;
    children?: Array<{
      _key: string;
    } & NavItem>;
    _key: string;
  }>;
  cta?: {
    text?: string;
    href?: string;
  };
  styles?: {
    theme?: "auto" | "light" | "dark";
    alignment?: "left" | "center" | "right";
    dropdownStyle?: "card" | "columns";
    density?: "comfortable" | "compact";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  announcement?: {
    enabled?: boolean;
    message?: string;
    href?: string;
    linkText?: string;
    variant?: "info" | "success" | "warning" | "alert";
    startAt?: string;
    endAt?: string;
  };
  theme?: {
    primaryColor?: ColorStyle;
    secondaryColor?: ColorStyle;
    accentColor?: ColorStyle;
    gradientFrom?: ColorStyle;
    gradientTo?: ColorStyle;
  };
  logo?: {
    logoType?: "svg" | "custom" | "original";
    customLogo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    svgColor?: "auto" | "dark" | "light";
    showCompanyText?: boolean;
    enableAnimation?: boolean;
  };
  company?: {
    name?: string;
    legalName?: string;
    alternateName?: string;
    websiteUrl?: string;
    tagline?: string;
    description?: string;
    foundingYear?: string;
    logoUrl?: string;
    coordinates?: {
      latitude?: string;
      longitude?: string;
    };
  };
  contact?: {
    phone?: string;
    email?: string;
    hrEmail?: string;
    legalEmail?: string;
    supportEmail?: string;
    address?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
  };
  social?: {
    linkedin?: string;
    twitter?: string;
    facebook?: string;
    twitterHandle?: string;
  };
  seo?: {
    defaultTitle?: string;
    defaultDescription?: string;
    defaultKeywords?: string;
    defaultOgImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    googleAnalyticsId?: string;
    googleVerificationCode?: string;
  };
};

export type ColorStyle = {
  _type: "colorStyle";
  color?: "#000000" | "#FFFFFF" | "#F8FAFC" | "#F1F5F9" | "#E2E8F0" | "#CBD5E1" | "#94A3B8" | "#64748B" | "#475569" | "#334155" | "#1E293B" | "#0F172A" | "#020617" | "#60A5FA" | "#3B82F6" | "#2563EB" | "#1D4ED8" | "#1E40AF" | "#818CF8" | "#6366F1" | "#4F46E5" | "#4338CA" | "#C084FC" | "#A855F7" | "#9333EA" | "#7E22CE" | "#22D3EE" | "#06B6D4" | "#0891B2" | "#0E7490" | "#2DD4BF" | "#14B8A6" | "#0D9488" | "#0F766E" | "#34D399" | "#10B981" | "#059669" | "#047857" | "#FB923C" | "#F97316" | "#EA580C" | "#C2410C" | "#F87171" | "#EF4444" | "#DC2626" | "#B91C1C";
  opacity?: number;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  industry?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "industry";
  };
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  subtitle?: string;
  client?: string;
  duration?: string;
  challenge?: string;
  solution?: string;
  results?: Array<{
    metric?: string;
    value?: string;
    description?: string;
    _key: string;
  }>;
  testimonial?: {
    quote?: string;
    author?: string;
    role?: string;
  };
  galleryImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  technologies?: Array<string>;
  certifications?: Array<string>;
  published?: boolean;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type JobPosting = {
  _id: string;
  _type: "jobPosting";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  department?: "Manufacturing" | "Quality Assurance" | "Engineering" | "Operations" | "Sales & Marketing" | "Administration";
  employmentType?: "Full-time" | "Part-time" | "Contract" | "Temporary";
  location?: string;
  shortDescription?: string;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  qualifications?: Array<string>;
  preferredQualifications?: Array<string>;
  benefits?: Array<string>;
  salaryRange?: string;
  applicationEmail?: string;
  applicationInstructions?: string;
  applicationLink?: string;
  published?: boolean;
  featured?: boolean;
  datePosted?: string;
  closingDate?: string;
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  bio?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  published?: boolean;
  order?: number;
  linkedin?: string;
  email?: string;
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  published?: boolean;
  excerpt?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & CalloutBox | {
    _key: string;
  } & ToleranceTable | {
    _key: string;
  } & ProcessFlow | {
    _key: string;
  } & MaterialData | {
    _key: string;
  } & EquipmentSpec | {
    _key: string;
  } & CtaButton>;
  category?: "manufacturing-processes" | "material-science" | "quality-compliance" | "industry-applications" | "calculators-tools";
  difficulty?: "beginner" | "intermediate" | "advanced";
  readTime?: string;
  publishDate?: string;
  author?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    attribution?: string;
    _type: "image";
  };
  featured?: boolean;
  tags?: Array<{
    tag?: string;
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    noindex?: boolean;
    keywords?: Array<{
      keyword?: string;
      _key: string;
    }>;
  };
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  published?: boolean;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    backgroundImageUrl?: string;
    badge?: string;
    subtitle?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    titleSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
    descriptionSize?: "xs" | "sm" | "base" | "lg" | "xl";
  };
  statistics?: Array<{
    value?: string;
    label?: string;
    description?: string;
    _key: string;
  }>;
  stats?: Array<{
    value?: string;
    label?: string;
    description?: string;
    _key: string;
  }>;
  expertiseSectionHeading?: string;
  expertiseSectionDescription?: string;
  expertise?: Array<{
    title?: string;
    description?: string;
    iconName?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    imageUrl?: string;
    componentsLabel?: string;
    components?: Array<string>;
    materials?: Array<string>;
    requirementsLabel?: string;
    requirements?: Array<string>;
    _key: string;
  }>;
  certificationsSectionHeading?: string;
  certificationsSectionDescription?: string;
  certifications?: Array<{
    title?: string;
    description?: string;
    iconName?: string;
    _key: string;
  }>;
  marketOverview?: {
    title?: string;
    description?: string;
    marketSize?: {
      title?: string;
      description?: string;
    };
    marketDrivers?: {
      title?: string;
      drivers?: Array<string>;
    };
  };
  overview?: {
    description?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    marketSize?: string;
    keyDrivers?: Array<{
      driver?: string;
      _key: string;
    }>;
    challenges?: Array<{
      challenge?: string;
      _key: string;
    }>;
  };
  capabilities?: Array<{
    title?: string;
    label?: string;
    value?: string;
    description?: string;
    technicalDetails?: Array<{
      detail?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  regulatory?: {
    certifications?: Array<{
      name?: string;
      description?: string;
      scope?: string;
      _key: string;
    }>;
    standards?: Array<{
      name?: string;
      description?: string;
      details?: Array<{
        detail?: string;
        _key: string;
      }>;
      _key: string;
    }>;
  };
  applications?: Array<{
    title?: string;
    description?: string;
    features?: Array<{
      feature?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  components?: Array<{
    category?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    imageUrl?: string;
    parts?: Array<{
      part?: string;
      _key: string;
    }>;
    materials?: Array<{
      material?: string;
      _key: string;
    }>;
    requirements?: Array<{
      requirement?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  qualityStandards?: Array<{
    title?: string;
    description?: string;
    details?: Array<{
      detail?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  processBenefitsSectionHeading?: string;
  processBenefitsSectionDescription?: string;
  processBenefits?: Array<{
    title?: string;
    description?: string;
    features?: Array<{
      feature?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  cta?: {
    heading?: string;
    description?: string;
    buttons?: Array<{
      text?: string;
      href?: string;
      variant?: "primary" | "secondary";
      enabled?: boolean;
      _key: string;
    }>;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    noindex?: boolean;
    keywords?: Array<{
      keyword?: string;
      _key: string;
    }>;
  };
  order?: number;
  iconName?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    attribution?: string;
    _type: "image";
  };
  imageUrl?: string;
  features?: Array<{
    feature?: string;
    _key: string;
  }>;
  cardCtaText?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  published?: boolean;
  shortDescription?: string;
  icon?: string;
  fullDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    badge?: string;
    subtitle?: string;
    title?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    titleSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
    descriptionSize?: "xs" | "sm" | "base" | "lg" | "xl";
  };
  overview?: {
    description?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  capabilities?: Array<{
    label?: string;
    value?: string;
    description?: string;
    _key: string;
  }>;
  services?: Array<{
    title?: string;
    description?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    featuresLabel?: string;
    capabilitiesLabel?: string;
    iconName?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    imageUrl?: string;
    bullets?: Array<{
      text?: string;
      _key: string;
    }>;
    features?: Array<{
      feature?: string;
      _key: string;
    }>;
    capabilities?: Array<{
      capability?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  servicesHeading?: string;
  servicesDescription?: string;
  servicesDescriptionRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  applicationsHeading?: string;
  applicationsDescription?: string;
  applicationsListLabel?: string;
  applications?: Array<{
    title?: string;
    description?: string;
    timeline?: string;
    listLabel?: string;
    challenges?: Array<{
      challenge?: string;
      _key: string;
    }>;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    imageUrl?: string;
    _key: string;
  }>;
  technicalSpecs?: Array<{
    spec?: string;
    value?: string;
    note?: string;
    _key: string;
  }>;
  process?: Array<{
    title?: string;
    description?: string;
    descriptionRich?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    features?: Array<{
      feature?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  equipment?: Array<{
    name?: string;
    details?: string;
    _key: string;
  }>;
  materialsHeading?: string;
  materialsDescription?: string;
  materials?: Array<{
    category?: string;
    types?: Array<{
      type?: string;
      _key: string;
    }>;
    applications?: string;
    _key: string;
  }>;
  qualityStandardsHeading?: string;
  qualityStandardsDescription?: string;
  qualityStandards?: Array<{
    title?: string;
    description?: string;
    iconName?: string;
    _key: string;
  }>;
  qualityImage?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    imageUrl?: string;
    alt?: string;
  };
  processHeading?: string;
  processDescription?: string;
  processes?: Array<{
    title?: string;
    description?: string;
    features?: Array<{
      feature?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    noindex?: boolean;
    keywords?: Array<{
      keyword?: string;
      _key: string;
    }>;
  };
  order?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    attribution?: string;
    _type: "image";
  };
  highlight?: boolean;
  cta?: {
    badge?: string;
    title?: string;
    description?: string;
    buttons?: Array<{
      text?: string;
      href?: string;
      variant?: "primary" | "secondary";
      enabled?: boolean;
      _key: string;
    }>;
  };
  specs?: Array<{
    spec?: string;
    _key: string;
  }>;
  cardCtaText?: string;
};

export type CtaSection = {
  _type: "ctaSection";
  title?: string;
  subtitle?: string;
  buttons?: Array<{
    text?: string;
    href?: string;
    variant?: "default" | "secondary";
    _key: string;
  }>;
  theme?: SectionTheme;
  titleColor?: ColorStyle;
  subtitleColor?: ColorStyle;
  buttonStyles?: {
    primaryButton?: {
      textColor?: ColorStyle;
      backgroundColor?: ColorStyle;
      borderColor?: ColorStyle;
      hoverBackgroundColor?: ColorStyle;
    };
    secondaryButton?: {
      textColor?: ColorStyle;
      backgroundColor?: ColorStyle;
      borderColor?: ColorStyle;
      hoverBackgroundColor?: ColorStyle;
    };
  };
  padding?: "small" | "medium" | "large" | "xlarge";
};

export type SectionTheme = {
  _type: "sectionTheme";
  backgroundColor?: ColorStyle;
  backgroundGradient?: {
    enabled?: boolean;
    fromColor?: ColorStyle;
    toColor?: ColorStyle;
    direction?: "to-b" | "to-t" | "to-r" | "to-l" | "to-tr" | "to-tl" | "to-br" | "to-bl";
  };
  textColor?: ColorStyle;
  accentColor?: ColorStyle;
};

export type RichTextSection = {
  _type: "richTextSection";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  container?: "default" | "narrow" | "wide" | "full";
  padding?: "none" | "small" | "medium" | "large";
  theme?: SectionTheme;
  headingStyles?: {
    h1?: TypographyStyle;
    h2?: TypographyStyle;
    h3?: TypographyStyle;
    h4?: TypographyStyle;
  };
  bodyTextStyle?: TypographyStyle;
  linkStyle?: {
    color?: ColorStyle;
    hoverColor?: ColorStyle;
    underline?: boolean;
  };
  blockquoteStyle?: {
    textColor?: ColorStyle;
    borderColor?: ColorStyle;
    backgroundColor?: ColorStyle;
  };
  codeStyle?: {
    textColor?: ColorStyle;
    backgroundColor?: ColorStyle;
  };
};

export type TypographyStyle = {
  _type: "typographyStyle";
  textColor?: ColorStyle;
  fontSize?: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | "6xl";
  fontWeight?: "normal" | "medium" | "semibold" | "bold" | "extrabold";
};

export type HeroSection = {
  _type: "heroSection";
  backgroundImageUrl?: string;
  imageAlt?: string;
  badge?: string;
  badgeIconName?: string;
  title?: string;
  titleHighlight?: string;
  description?: string;
  buttons?: Array<{
    label?: string;
    href?: string;
    variant?: "primary" | "secondary";
    _key: string;
  }>;
  alignment?: "left" | "center" | "right";
  height?: "large" | "full" | "medium";
  titleColor?: ColorStyle;
  titleHighlightColor?: ColorStyle;
  descriptionColor?: ColorStyle;
  badgeStyle?: {
    textColor?: ColorStyle;
    backgroundColor?: ColorStyle;
    borderColor?: ColorStyle;
  };
  overlay?: {
    enabled?: boolean;
    color?: ColorStyle;
  };
  buttonStyles?: {
    primaryButton?: {
      textColor?: ColorStyle;
      backgroundColor?: ColorStyle;
      borderColor?: ColorStyle;
    };
    secondaryButton?: {
      textColor?: ColorStyle;
      backgroundColor?: ColorStyle;
      borderColor?: ColorStyle;
    };
  };
};

export type NavGroup = {
  _type: "navGroup";
  groupTitle?: string;
  items?: Array<{
    _key: string;
  } & NavItem>;
};

export type NavItem = {
  _type: "navItem";
  name?: string;
  href?: string;
  description?: string;
  iconPreset?: "none" | "home" | "info" | "services" | "industries" | "resources" | "terms" | "supplier-requirements" | "careers" | "jobs" | "layers" | "contact" | "phone" | "mail" | "book" | "wrench" | "building2" | "shield" | "file-text" | "custom";
  iconName?: string;
  linkType?: "internal" | "external" | "anchor";
  openInNewTab?: boolean;
  showInHeader?: boolean;
  showInMobile?: boolean;
  showInFooter?: boolean;
  style?: {
    variant?: "link" | "button-primary" | "button-secondary" | "badge";
    badgeText?: string;
  };
  children?: Array<{
    _key: string;
  } & NavItem | {
    _key: string;
  } & NavGroup>;
};

export type CtaButton = {
  _type: "ctaButton";
  text?: string;
  href?: string;
  variant?: "primary" | "secondary" | "outline";
  customStyle?: {
    enabled?: boolean;
    textColor?: ColorStyle;
    backgroundColor?: ColorStyle;
    borderColor?: ColorStyle;
    hoverTextColor?: ColorStyle;
    hoverBackgroundColor?: ColorStyle;
    hoverBorderColor?: ColorStyle;
  };
  size?: "sm" | "md" | "lg" | "xl";
  fullWidth?: boolean;
  trackingEvent?: string;
};

export type EquipmentSpec = {
  _type: "equipmentSpec";
  equipmentName?: string;
  manufacturer?: string;
  model?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  specifications?: Array<{
    parameter?: string;
    value?: string;
    unit?: string;
    tolerance?: string;
    _key: string;
  }>;
  applications?: string;
  advantages?: string;
};

export type MaterialData = {
  _type: "materialData";
  materialName?: string;
  grade?: string;
  description?: string;
  properties?: Array<{
    property?: string;
    value?: string;
    unit?: string;
    testMethod?: string;
    _key: string;
  }>;
  applications?: string;
  machiningConsiderations?: string;
};

export type ProcessFlow = {
  _type: "processFlow";
  title?: string;
  description?: string;
  steps?: Array<{
    stepNumber?: number;
    title?: string;
    description?: string;
    duration?: string;
    tools?: Array<string>;
    qualityCheck?: string;
    _key: string;
  }>;
};

export type ToleranceTable = {
  _type: "toleranceTable";
  title?: string;
  description?: string;
  headers?: Array<string>;
  rows?: Array<{
    cells?: Array<string>;
    _key: string;
  }>;
};

export type CalloutBox = {
  _type: "calloutBox";
  type?: "info" | "warning" | "success" | "error" | "tip";
  title?: string;
  content?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Page | SanityImageCrop | SanityImageHotspot | Slug | PageContent | UiText | Metbase | ErrorPages | SupplierRequirements | Terms | Careers | Contact | About | Footer | IndustriesPage | ServicesPage | Homepage | Navigation | SiteSettings | ColorStyle | CaseStudy | JobPosting | TeamMember | Resource | Industry | Service | CtaSection | SectionTheme | RichTextSection | TypographyStyle | HeroSection | NavGroup | NavItem | CtaButton | EquipmentSpec | MaterialData | ProcessFlow | ToleranceTable | CalloutBox | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
